# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  imageName: 'v1/apptest1'

stages:
- stage: Build
  displayName: Build image app test
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        repository: $(imageName)
        command: build
        Dockerfile: _Docker/Dockerfile
        tags: |
          $(tag)
    - task: Docker@2
      inputs:
        containerRegistry: 'connexiontomouradresgitry'
        repository: 'v1/apptest1'
        command: 'push'

